circuit_application.o: circuit_application.c circuit_application.h
circuit_gui.o: circuit_gui.c \
 /home/jfeng/Project/comps/graphics/imgui/zmw-0.2.1/include/zmw/zmw.h \
 /home/jfeng/Project/comps/graphics/imgui/zmw-0.2.1/include/zmw/zmw_generated_public.h \
 /home/jfeng/Project/comps/graphics/imgui/zmw-0.2.1/include/zmw/zmw_widgets.h \
 /home/jfeng/Project/comps/graphics/imgui/zmw-0.2.1/include/zmw/http.h \
 circuit_application.h
