accel.o: accel.c
anchor_box.o: anchor_box.c
animation.o: animation.c
asked.o: asked.c
button.o: button.c
color.o: color.c
compose.o: compose.c
cursorin.o: cursorin.c
drag_and_drop.o: drag_and_drop.c
dragger.o: dragger.c
editable_text.o: editable_text.c
embeded.o: embeded.c
expand.o: expand.c
filechooser.o: filechooser.c
focus.o: focus.c
hello_world.o: hello_world.c
hor_hor_box.o: hor_hor_box.c
horizontal_box.o: horizontal_box.c
image.o: image.c
main.o: main.c \
 /home/jfeng/Project/comps/graphics/imgui/zmw-0.2.1/include/zmw/zmw.h \
 /home/jfeng/Project/comps/graphics/imgui/zmw-0.2.1/include/zmw/zmw_generated_public.h \
 /home/jfeng/Project/comps/graphics/imgui/zmw-0.2.1/include/zmw/zmw_widgets.h \
 /home/jfeng/Project/comps/graphics/imgui/zmw-0.2.1/include/zmw/http.h \
 hello_world.c editable_text.c horizontal_box.c expand.c hor_hor_box.c \
 ver_ver_box.c ver_hor_box.c vertical_box.c many_widgets.c color.c \
 focus.c button.c menu.c notebook.c tips.c drag_and_drop.c toggle.c \
 quit.c asked.c dragger.c animation.c anchor_box.c scrollbar.c \
 scrollbar2.c viewport.c embeded.c sensible.c state.c accel.c \
 filechooser.c image.c compose.c message.c test_trace.c table.c \
 cursorin.c
main_sb.o: main_sb.c \
 /home/jfeng/Project/comps/graphics/imgui/zmw-0.2.1/include/zmw/zmw.h \
 /home/jfeng/Project/comps/graphics/imgui/zmw-0.2.1/include/zmw/zmw_generated_public.h \
 /home/jfeng/Project/comps/graphics/imgui/zmw-0.2.1/include/zmw/zmw_widgets.h \
 /home/jfeng/Project/comps/graphics/imgui/zmw-0.2.1/include/zmw/http.h
main_trace.o: main_trace.c \
 /home/jfeng/Project/comps/graphics/imgui/zmw-0.2.1/include/zmw/zmw.h \
 /home/jfeng/Project/comps/graphics/imgui/zmw-0.2.1/include/zmw/zmw_generated_public.h \
 /home/jfeng/Project/comps/graphics/imgui/zmw-0.2.1/include/zmw/zmw_widgets.h \
 /home/jfeng/Project/comps/graphics/imgui/zmw-0.2.1/include/zmw/http.h \
 test_trace.c many_widgets.c notebook.c
many_widgets.o: many_widgets.c
menu.o: menu.c
message.o: message.c
notebook.o: notebook.c
quit.o: quit.c
scrollbar.o: scrollbar.c
scrollbar2.o: scrollbar2.c
sensible.o: sensible.c
state.o: state.c
table.o: table.c
test_trace.o: test_trace.c
tips.o: tips.c
toggle.o: toggle.c
ver_hor_box.o: ver_hor_box.c
ver_ver_box.o: ver_ver_box.c
vertical_box.o: vertical_box.c
viewport.o: viewport.c
